# Generated by Django 5.2.7 on 2025-10-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='called_numbers',
        ),
    ]
