# Generated by Django 5.2.7 on 2025-10-10 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_game_called_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='RoundWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.PositiveIntegerField()),
                ('pattern_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_wise', to='core.game')),
                ('won_by', models.ManyToManyField(blank=True, related_name='won_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game', 'round_id'],
                'unique_together': {('game', 'round_id', 'pattern_id')},
            },
        ),
    ]
