# Generated by Django 5.2.7 on 2025-10-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='user',
            new_name='used',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='created_at',
        ),
    ]
