# Generated by Django 5.2.7 on 2025-10-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_tickets_used_remove_tickets_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundwise',
            name='patternName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundwise',
            name='prize_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
