# Generated by Django 5.2.7 on 2025-11-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_roundwise_patternname_roundwise_prize_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(default='upcoming', max_length=50),
        ),
    ]
