# Generated by Django 5.2.7 on 2025-11-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('completed', 'Completed')], default='upcoming', max_length=50),
        ),
    ]
